ALTER TABLE orders ADD COLUMN IF NOT EXISTS payment_method VARCHAR(255);
ALTER TABLE orders ADD COLUMN IF NOT EXISTS payment_status VARCHAR(255) DEFAULT 'PENDING';
ALTER TABLE orders ADD COLUMN IF NOT EXISTS transaction_id VARCHAR(255);
